function template(locals) {
var jade_debug = [{ lineno: 1, filename: "index.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (undefined) {
var jade_indent = [];
jade_debug.unshift({ lineno: 0, filename: "index.jade" });
jade_debug.unshift({ lineno: 1, filename: "index.jade" });
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "index.jade" });
buf.push("\n<html lang=\"es\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "index.jade" });
buf.push("\n  <head>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "index.jade" });
buf.push("\n    <meta charset=\"UTF-8\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "index.jade" });
buf.push("\n    <title>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("Plataforma Educativa");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "index.jade" });
buf.push("\n    <link rel=\"shortcut icon\" href=\"img/favicon.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "index.jade" });
buf.push("\n    <link rel=\"stylesheet\" href=\"css/estilo.css\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n  </head>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "index.jade" });
buf.push("\n  <body>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: "index.jade" });
buf.push("\n    <div class=\"todo\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: "index.jade" });
buf.push("\n      <header class=\"grid grid-pad cabecera\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: "index.jade" });
buf.push("\n        <div class=\"col-3-12 centro\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: "index.jade" });
buf.push("\n          <div class=\"logo\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: "index.jade" });
buf.push("<a href=\"#\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: "index.jade" });
buf.push("<img src=\"img/logo_plataforma.png\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n        </div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "index.jade" });
buf.push("\n        <div class=\"col-6-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "index.jade" });
buf.push("\n        <div class=\"col-3-12 centro\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n      </header>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "index.jade" });
buf.push("\n      <div class=\"medio\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "index.jade" });
buf.push("\n        <div class=\"grid grid-pad menos\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 22, filename: "index.jade" });
buf.push("\n          <div class=\"col-2-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 23, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "index.jade" });
buf.push("\n          <div class=\"col-7-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 26, filename: "index.jade" });
buf.push("\n          <div class=\"col-3-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 27, filename: "index.jade" });
buf.push("\n            <div class=\"login\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 28, filename: "index.jade" });
buf.push("\n              <form action=\"\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.unshift({ lineno: 29, filename: "index.jade" });
buf.push("\n              <div class=\"entrar tabla\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: "index.jade" });
buf.push("<span class=\"texte\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: jade_debug[0].filename });
buf.push("Entrar");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 31, filename: "index.jade" });
buf.push("\n              <div class=\"tabla\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: "index.jade" });
buf.push("\n                <h7>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: jade_debug[0].filename });
buf.push("Nombre de Usuario");
jade_debug.shift();
jade_debug.shift();
buf.push("</h7>");
jade_debug.shift();
jade_debug.unshift({ lineno: 33, filename: "index.jade" });
buf.push("\n                <input type=\"text\" title=\"usuario\" class=\"input\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "index.jade" });
buf.push("\n                <h7>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 34, filename: jade_debug[0].filename });
buf.push("Contraseña");
jade_debug.shift();
jade_debug.shift();
buf.push("</h7>");
jade_debug.shift();
jade_debug.unshift({ lineno: 35, filename: "index.jade" });
buf.push("\n                <input type=\"password\" title=\"contraseña\" class=\"input\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n              </div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 36, filename: "index.jade" });
buf.push("\n              <div class=\"tabla centro\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 37, filename: "index.jade" });
buf.push("\n                <input type=\"submit\" value=\"Entrar\" class=\"boton\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n              </div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 38, filename: "index.jade" });
buf.push("\n              <div class=\"peq1\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 39, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 39, filename: jade_debug[0].filename });
buf.push("¿Has Olvidado tu contraseña?");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n            </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n          </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n        </div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 40, filename: "index.jade" });
buf.push("\n        <div class=\"grid grid-pad palto\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: "index.jade" });
buf.push("\n          <div class=\"col-1-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 42, filename: "index.jade" });
buf.push("\n            <div class=\"red\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 43, filename: "index.jade" });
buf.push("<img src=\"img/logo_red.png\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n          </div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 44, filename: "index.jade" });
buf.push("\n          <div class=\"col-8-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 46, filename: "index.jade" });
buf.push("\n          <div class=\"col-3-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 47, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n        </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n      </div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 48, filename: "index.jade" });
buf.push("\n      <div class=\"ultimasnot\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 49, filename: "index.jade" });
buf.push("\n        <div class=\"grid grid-pad\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: "index.jade" });
buf.push("\n          <div class=\"col-3-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 51, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 51, filename: jade_debug[0].filename });
buf.push("ultimas noticias");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 52, filename: "index.jade" });
buf.push("\n          <div class=\"col-8-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 54, filename: "index.jade" });
buf.push("\n          <div class=\"col-1-12\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 55, filename: "index.jade" });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n        </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n      </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n    </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n  </body>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n</html>");
jade_debug.shift();
jade_debug.shift();}("undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "<!DOCTYPE html>\r\nhtml(lang=\"es\")\r\n\thead\r\n\t\tmeta(charset=\"UTF-8\")\r\n\t\ttitle Plataforma Educativa\r\n\t\tlink(rel=\"shortcut icon\", href=\"img/favicon.png\")\r\n\t\tlink(rel=\"stylesheet\", href=\"css/estilo.css\")\r\n\tbody\r\n\t\t.todo\r\n\t\t\theader.grid.grid-pad.cabecera\r\n\t\t\t\t.col-3-12.centro\r\n\t\t\t\t\t.logo\r\n\t\t\t\t\t\ta(href=\"#\")\r\n\t\t\t\t\t\t\timg(src=\"img/logo_plataforma.png\")\r\n\t\t\t\t.col-6-12\r\n\t\t\t\t\t&nbsp;\r\n\t\t\t\t.col-3-12.centro\r\n\t\t\t\t\t&nbsp;\r\n\t\t\t.medio\r\n\t\t\t\t//- img(src=\"\", class=\"imagen\")\r\n\t\t\t\t.grid.grid-pad.menos\r\n\t\t\t\t\t.col-2-12\r\n\t\t\t\t\t\t&nbsp;\r\n\t\t\t\t\t.col-7-12\r\n\t\t\t\t\t\t&nbsp;\r\n\t\t\t\t\t.col-3-12\r\n\t\t\t\t\t\t.login\r\n\t\t\t\t\t\t\tform(action=\"\")\r\n\t\t\t\t\t\t\t.entrar.tabla\r\n\t\t\t\t\t\t\t\tspan.texte Entrar\r\n\t\t\t\t\t\t\t.tabla\r\n\t\t\t\t\t\t\t\th7 Nombre de Usuario\r\n\t\t\t\t\t\t\t\tinput(type=\"text\" title=\"usuario\" class=\"input\")\r\n\t\t\t\t\t\t\t\th7 Contraseña\r\n\t\t\t\t\t\t\t\tinput(type=\"password\" title=\"contraseña\" class=\"input\")\r\n\t\t\t\t\t\t\t.tabla.centro\r\n\t\t\t\t\t\t\t\tinput(type=\"submit\" class=\"boton\" value=\"Entrar\")\r\n\t\t\t\t\t\t\t.peq1\r\n\t\t\t\t\t\t\t\tspan ¿Has Olvidado tu contraseña?\r\n\t\t\t\t.grid.grid-pad.palto\r\n\t\t\t\t\t.col-1-12\r\n\t\t\t\t\t\t.red\r\n\t\t\t\t\t\t\timg(src=\"img/logo_red.png\")\r\n\t\t\t\t\t.col-8-12\r\n\t\t\t\t\t\t&nbsp;\r\n\t\t\t\t\t.col-3-12\r\n\t\t\t\t\t\t&nbsp;\r\n\t\t\t.ultimasnot\r\n\t\t\t\t.grid.grid-pad\r\n\t\t\t\t\t\t.col-3-12\r\n\t\t\t\t\t\t\tspan ultimas noticias\r\n\t\t\t\t\t\t.col-8-12\r\n\t\t\t\t\t\t\t&nbsp;\r\n\t\t\t\t\t\t.col-1-12\r\n\t\t\t\t\t\t\t&nbsp;\r\n\r\n\r\n");
}
}